config/routes.rb
Rails.application.routes.draw do
  resources :content_items
  root to: 'content_items#new'
  get 'search_form' => "content_items#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/add_start_time_to_content_item.rb
class AddStartTimeToContentItem < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content_item.rb
class ContentItem < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/content_items_controller.rb
class ContentItemsController < ApplicationController
  before_action :set_content_item, only: %i[ show edit update destroy ]

  # GET /content_items or /content_items.json
  def index
    @content_items = ContentItem.all
  end

  # GET /content_items/1 or /content_items/1.json
  def show
  end

  # GET /content_items/new
  def new
    puts params
    @content_item = ContentItem.new
    if params[:search].present? || params[:network].present?
      @content_items = ContentItem.where("content_title LIKE ? AND publishing_target LIKE ?", "%#{params[:search]}%", "%#{params[:network]}%") 
    elsif params[:search].present?
      @content_items = ContentItem.where("content_title LIKE ?", "%#{params[:search]}%") 
    elsif params[:network].present?
      @content_items = ContentItem.where("publishing_target LIKE ?","%#{params[:network]}%") 
    else
      @content_items = ContentItem.all
    end
  end

  # GET /content_items/1/edit
  def edit
  end

  # POST /content_items or /content_items.json
  def create
    @content_item = ContentItem.new(content_item_params)

    respond_to do |format|
      if @content_item.save
        format.html { redirect_to content_item_url(@content_item), notice: "Content item was successfully created." }
        format.json { render :show, status: :created, location: @content_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content_items/1 or /content_items/1.json
  def update
    respond_to do |format|
      if @content_item.update(content_item_params)
        format.html { redirect_to content_item_url(@content_item), notice: "Content item was successfully updated." }
        format.json { render :show, status: :ok, location: @content_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_items/1 or /content_items/1.json
  def destroy
    @content_item.destroy

    respond_to do |format|
      format.html { redirect_to content_items_url, notice: "Content item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_item
      @content_item = ContentItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_item_params
      params.require(:content_item).permit(:content_title, :publishing_target, :publish_date, :start_time, :end_time)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
    @meetings = Meeting.all
  end

  # GET /meetings/  1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_items_helper.rb
module ContentItemsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/content_items/_form.html.erb
<%= form_with(model: content_item) do |form| %>
  <% if content_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content_item.errors.count, "error") %> prohibited this content_item from being saved:</h2>

      <ul>
        <% content_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Event Title</label>
    <%= form.text_field :content_title %>
  </div>

  <div class="field">
    <label>Network</label>
    <%= form.select :publishing_target, ['facebook', 'YouTube']%>

  </div>

  <div class="field">
    <%= form.label :publish_date %>
    <%= form.datetime_select :publish_date %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/content_items/edit.html.erb
<h1>Editing Content Item</h1>

<%= render 'form', content_item: @content_item %>

<%= link_to 'Show', @content_item %> |
<%= link_to 'Back', content_items_path %>

app/views/content_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Content Items</h1>

<table>
  <thead>
    <tr>
      <th>Content title</th>
      <th>Publishing target</th>
      <th>Publish date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @content_items.each do |content_item| %>
      <tr>
        <td><%= content_item.content_title %></td>
        <td><%= content_item.publishing_target %></td>
        <td><%= content_item.publish_date %></td>
        <td><%= link_to 'Show', content_item %></td>
        <td><%= link_to 'Edit', edit_content_item_path(content_item) %></td>
        <td><%= link_to 'Destroy', content_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content Item', new_content_item_path %>

app/views/content_items/new.html.erb
<div class="form-panel">
<h1>New Content Item</h1>
<%= render 'form', content_item: @content_item %>
</div>
<br/>
<br/>
<div class="search-panel">
	<%= form_with(url: '/search_form', method: 'get', local: true) do %>
  		<%= text_field_tag(:search) %>
  		<%= select_tag 'network', options_for_select([['facebook', 'facebook'],['YouTube', 'YouTube']]) %>
  		<%= submit_tag("Go") %>
	<% end %>
</div>
<br/>
<div>
	<%= month_calendar(events: @content_items) do |date, content_items| %>
  		<%= date %>
  		<% content_items.each do |content_item| %>
    		<div>
      			<%= content_item.content_title %> | <%= content_item.publishing_target %>
    		</div>
  		<% end %>
	<% end %>
</div>

app/views/content_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content title:</strong>
  <%= @content_item.content_title %>
</p>

<p>
  <strong>Publishing target:</strong>
  <%= @content_item.publishing_target %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @content_item.publish_date %>
</p>

<%= link_to 'Edit', edit_content_item_path(@content_item) %> |
<%= link_to 'Back', content_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventIntegration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>